### ISSUE TITLE
value (global 'error')

### ISSUE THREAD

**Issue by aleyner** [odkr/pandoc-quotes.lua#9]
Hello!
I installed a new version of pandoc 3.1.6.2 [windows-x86_64.msi] and the filter stopped working, it gives this error. What should I do?

Transcript started, output file is build.log
Executing Pandoc...
Error running filter C:\Users\...\pandoc-quotes.lua:
...ers\...\pandoc-quotes.lua:465: attempt to call a nil value (global 'error')
stack traceback:
Write-Error: Pandoc execution has failed

**Comment by odkr** [comment]
Hey, sorry, I was sick last week. Since you closed the issue, I assume you figured it out?
